### ISSUE TITLE
[Question] How to versioning the rules today?

### ISSUE THREAD

**Issue by LaurentDardenne** [BernieWhite/PSRule#215]
For a module, manage them with Import-Module and -Requiredversion?

For a script, add information via PSGet or add a version number to the directory name of the rule?

**Comment by BernieWhite** [comment]
@LaurentDardenne Modules are the intended packaging process to distribute rules.

Modules already load the newest based on version number by default with `Import-Module <moduleName>`. Since PSRule currently uses only imported modules it complements this management scheme.

Can you think of a good reason to support single file distributions of rules?

**Comment by BernieWhite** [comment]
@LaurentDardenne I hope I answered your question :).

It is probably a good one for an FAQ.

**Comment by LaurentDardenne** [comment]
> Can you think of a good reason to support single file distributions of rules?

No, I'm looking at how PSRule works, what it offers, and how to best implement it.

> I hope I answered your question :).

Absolutely.Thank you.
